function Hd = Filter5
%FILTER5 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 06-Nov-2023 16:09:55

% Generalized REMEZ FIR Lowpass filter designed using the FIRGR function.

% All frequency values are in kHz.
Fs = 8;  % Sampling Frequency

Fpass = 2;               % Passband Frequency
Fstop = 3.462;           % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 20;              % Density Factor
phase = 'minphase';      % Phase Specification

% Calculate the coefficients using the FIRGR function.
b  = firgr('minorder', [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Dpass ...
           Dstop], {dens}, phase);
Hd = dfilt.dffir(b);

% [EOF]
